// Game
const CANVAS_HEIGHT = 500;
const CANVAS_WIDTH = 700;

// Ship
const ROCKET_HEIGHT = 15;
const ROCKET_WIDTH = 10;

// Asteroid
const LARGE_ASTEROID_SIZE = 50;
const LARGE_ASTEROID_FLIGHT_SPEED = 1;
const LARGE_ASTEROID_ROTATION_MODIFIER = 0.005;
const MIN_ASTEROID_SPAWN_DISTANCE = 200;
const LARGE_ASTEROID_RADIUS_CLAMP = 0.5;

// Math
const TAU = 2 * Math.PI;

export {
  CANVAS_WIDTH,
  CANVAS_HEIGHT,
  ROCKET_WIDTH,
  ROCKET_HEIGHT,
  LARGE_ASTEROID_ROTATION_MODIFIER,
  LARGE_ASTEROID_SIZE,
  LARGE_ASTEROID_FLIGHT_SPEED,
  LARGE_ASTEROID_RADIUS_CLAMP,
  MIN_ASTEROID_SPAWN_DISTANCE,
  TAU,
};
